# Site settings
title: mumbi
name: 임준환 # your name
email: mumbi@daum.net # your email address
description: >
    description. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mumbi.github.io" # the base hostname & protocol for your site
twitter_username:  # your Twitter username
github_username: mumbi # your Github username
disqus_username: joonanism # your disqus username

google-analytics: UA-75034651-1 # add it if you have one

skillstree: false # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
