title: mumbi
description: Techniques
author: mumbi
logo: /static/img/avatar.png
github: https://github.com/mumbi
about: developer

baseurl: ""
url: "https://mumbi.github.io"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
